name: Kotlin CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Set up Node 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          POLYGON_APIKEY: ${{ secrets.POLYGON_APIKEY }}
          POLYGON_SECRET: ${{ secrets.POLYGON_SECRET }}
          BACS_USERNAME: ${{ secrets.BACS_USERNAME }}
          BACS_PASSWORD: ${{ secrets.BACS_PASSWORD }}
          SYBON_APIKEY: ${{ secrets.SYBON_APIKEY }}
